# Generated by Django 3.0.5 on 2020-07-26 05:21

import accounts.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=254, null=True)),
                ('role', models.CharField(choices=[('Controller', 'Controller'), ('Teacher', 'Teacher'), ('Web Developer', 'Web Developer'), ('Others', 'Others')], default='Teacher', max_length=20)),
                ('designation', models.CharField(choices=[('Principle', 'Principle'), ('Vice-Principle', 'Vice-Principle'), ('Accountant', 'Accountant'), ('CI', 'CI'), ('Junior Instructor', 'Junior Instructor'), ('Instructor', 'Instructor'), ('Other', 'Other')], default='Junior Instructor', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=14, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('nationality', models.CharField(default='Bangladeshi', max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s.\\-]*$', "Only characters are allowed. Don't use number")])),
                ('religion', models.CharField(blank=True, choices=[('Islam', 'Islam'), ('Hinduism', 'Hinduism'), ('Christianity', 'Christianity'), ('Buddhism', 'Buddhism')], default='Islam', max_length=50, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Common', 'Common')], default='Male', max_length=10)),
                ('blood_group', models.CharField(blank=True, max_length=3, null=True)),
                ('present_address', models.TextField(blank=True, null=True, verbose_name='Present Address')),
                ('permanent_address', models.TextField(blank=True, null=True, verbose_name='Permanent Address')),
                ('image', models.ImageField(default='default-user.jpg', help_text='Upload your recent photo. Image must be 200px or more both in height and width', max_length=120, upload_to='staffs/', validators=[accounts.validators.validate_image])),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staffs.Staff')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
