# Generated by Django 3.0.5 on 2020-07-26 05:21

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(help_text='Example: 1st, 2nd, 3rd etc.', max_length=3, unique=True, verbose_name='Batch No')),
                ('session', models.CharField(help_text='Example: 2019-2020', max_length=9, unique=True)),
                ('regulation', models.CharField(default='2016', max_length=4)),
                ('admission_start', models.DateField(default=django.utils.timezone.now)),
                ('admission_end', models.DateField(default=datetime.date(2020, 8, 25))),
                ('maintain_date', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Batches',
            },
        ),
    ]
