# Generated by Django 3.0.5 on 2020-07-26 05:21

import courses.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_hand', models.CharField(default='-T', max_length=5)),
                ('code', models.CharField(max_length=3)),
                ('course_type', models.CharField(choices=[('Diploma in Engineering', 'Diploma in Engineering'), ('Trade Course', 'Trade Course')], default='Diploma in Engineering', max_length=100)),
                ('admission_fee', models.IntegerField(default=5000, verbose_name='Admission Fee')),
                ('readmission_fee', models.IntegerField(default=0, verbose_name='Re-admission Fee')),
                ('semeseters', models.IntegerField(default=8, verbose_name='No. of semesters')),
                ('duration', models.CharField(choices=[('4 Years', '4 Years')], default='4 Years', max_length=100)),
                ('image', models.ImageField(default='1280x640.png', help_text='Image size: 1280x640', upload_to='courses', validators=[courses.validators.validate_image])),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
